// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode fieldsfirst 

package grim3212.ultimatefist;

import java.util.logging.Level;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "UltimateFist", name = "Ultimate Fist", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class UltimateFistCore {

	@SidedProxy(clientSide = "grim3212.ultimatefist.common.ClientProxy", serverSide = "grim3212.ultimatefist.common.CommonProxy")
	public static grim3212.ultimatefist.common.CommonProxy proxy;
	@Instance("UltimateFist")
	public static UltimateFistCore instance;

	public static Item ultimateFist;
	public int ufID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {

		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Ultimate Fist";
		data.description = "Adds in a item that can basically break any block with one hit.";
		data.authorList.add("Grim3212");
		data.authorList.add("Bricanyl");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Bricanyl for the original mod.";
		data.logoFile = "/mods/logo.png";

		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			ufID = config.get(Configuration.CATEGORY_ITEM, "Ultimate Fist ID", 9068).getInt(9068);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Ultimate Fist has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();

		ultimateFist = (new UltimateFist(ufID)).setUnlocalizedName("UltimateFist").setCreativeTab(CreativeTabs.tabTools);
		LanguageRegistry.addName(ultimateFist, "UltimateFist");
		GameRegistry.addRecipe(new ItemStack(ultimateFist, 1), new Object[] { "XXX", "X##", "XXX", Character.valueOf('#'), Item.leather, Character.valueOf('X'), Item.diamond });
	}
}
