// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode 

package grim3212.multitools;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.EnumHelper;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

// Referenced classes of package net.minecraft.src:
//            BaseMod, ModLoader, Item, ItemStack, 
//            Block, ItemMultiTool, mod_EnumToolMaterial
@Mod(modid = "MultiTools", name = "Multi Tools", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class MultiTools {
	
	@SidedProxy(clientSide = "grim3212.multitools.common.ClientProxy", serverSide = "grim3212.multitools.common.CommonProxy")
	public static grim3212.multitools.common.CommonProxy proxy;
	@Instance("MultiTools")
	public static MultiTools instance;
	
	public static Item DMultiTool;
	public static Item WMultiTool;
	public static Item SMultiTool;
	public static Item IMultiTool;
	public static Item GMultiTool;
	public static Item OMultiTool;
	
	public int dMT;
	public int wMT;
	public int sMT;
	public int iMT;
	public int gMT;
	public int oMT;

	public static EnumToolMaterial oTM = EnumHelper.addToolMaterial("oTM", 11, 10000, 42.0F, 11, 14);
	
	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "MultiTools";
    	data.description = "Adds a bunch of tools that are mixes of all of the tools like pickaxes and swords and shovels etc.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("AlexM");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to AlexM for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			dMT = config.get(Configuration.CATEGORY_ITEM, "Diamond MultiTool ID", 9046).getInt(9046);
			wMT = config.get(Configuration.CATEGORY_ITEM, "Wood MultiTool ID", 9047).getInt(9047);
			sMT = config.get(Configuration.CATEGORY_ITEM, "Stone MultiTool ID", 9048).getInt(9048);
			iMT = config.get(Configuration.CATEGORY_ITEM, "Iron MultiTool ID", 9049).getInt(9049);
			gMT = config.get(Configuration.CATEGORY_ITEM, "Gold MultiTool ID", 9050).getInt(9050);
			oMT = config.get(Configuration.CATEGORY_ITEM, "Obsidian MultiTool ID", 9051).getInt(9051);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Multi Tools has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();

		DMultiTool = (new ItemMultiTool(dMT, EnumToolMaterial.EMERALD)).setUnlocalizedName("DMultiTool");
		WMultiTool = (new ItemMultiTool(wMT, EnumToolMaterial.WOOD)).setUnlocalizedName("WMultiTool");
		SMultiTool = (new ItemMultiTool(sMT, EnumToolMaterial.STONE)).setUnlocalizedName("SMultiTool");
		IMultiTool = (new ItemMultiTool(iMT, EnumToolMaterial.IRON)).setUnlocalizedName("IMultiTool");
		GMultiTool = (new ItemMultiTool(gMT, EnumToolMaterial.GOLD)).setUnlocalizedName("GMultiTool");
		OMultiTool = (new ItemMultiTool(oMT, this.oTM)).setUnlocalizedName("OMultiTool");
		
		MinecraftForge.setToolClass(OMultiTool, "pickaxe", 3);
		LanguageRegistry.addName(DMultiTool, "Diamond MultiTool");
		LanguageRegistry.addName(WMultiTool, "Wood MultiTool");
		LanguageRegistry.addName(SMultiTool, "Stone MultiTool");
		LanguageRegistry.addName(IMultiTool, "Iron MultiTool");
		LanguageRegistry.addName(GMultiTool, "Gold MultiTool");
		LanguageRegistry.addName(OMultiTool, "Obsidian MultiTool");
		GameRegistry.addShapelessRecipe(new ItemStack(DMultiTool, 1), new Object[] { Item.swordDiamond, Item.pickaxeDiamond, Item.shovelDiamond, Item.hoeDiamond, Item.axeDiamond, Item.diamond, Item.diamond, Item.diamond, Item.diamond });
		GameRegistry.addShapelessRecipe(new ItemStack(GMultiTool, 1), new Object[] { Item.swordGold, Item.pickaxeGold, Item.shovelGold, Item.hoeGold, Item.axeGold, Item.ingotGold, Item.ingotGold, Item.ingotGold, Item.ingotGold });
		GameRegistry.addShapelessRecipe(new ItemStack(WMultiTool, 1), new Object[] { Item.swordWood, Item.pickaxeWood, Item.shovelWood, Item.hoeWood, Item.axeWood, Block.wood, Block.wood, Block.wood, Block.wood });
		GameRegistry.addShapelessRecipe(new ItemStack(SMultiTool, 1), new Object[] { Item.swordStone, Item.pickaxeStone, Item.shovelStone, Item.hoeStone, Item.axeStone, Block.cobblestone, Block.cobblestone, Block.cobblestone, Block.cobblestone });
		GameRegistry.addShapelessRecipe(new ItemStack(IMultiTool, 1), new Object[] { Item.swordSteel, Item.pickaxeSteel, Item.shovelSteel, Item.hoeSteel, Item.axeSteel, Item.ingotIron, Item.ingotIron, Item.ingotIron, Item.ingotIron });
		GameRegistry.addShapelessRecipe(new ItemStack(OMultiTool, 1), new Object[] { DMultiTool, GMultiTool, WMultiTool, SMultiTool, IMultiTool, Block.obsidian, Block.obsidian, Block.obsidian, Block.obsidian });

	}
	
}
