package grim3212.raygun;

import grim3212.raygun.common.Sounds;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Raygun", name = "Raygun", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Raygun {
	@SidedProxy(clientSide = "grim3212.raygun.common.ClientProxy", serverSide = "grim3212.raygun.common.CommonProxy")
	public static grim3212.raygun.common.CommonProxy proxy;
	@Instance("Raygun")
	public static Raygun instance;

	public static Block element;
	public static Item rayeItem;
	public static Item elemItem;
	public static Item rayeeItem;
	public static Item raygItem;
	public static Item advrayeeItem;
	public static Item advrayeItem;
	public static Item advraygItem;
	public static Item ingotIronDark;

	public int elementID;
	public int rayeItemID;
	public int elemID;
	public int rayeeItemID;
	public int rayGItemID;
	public int advrayeeItemID;
	public int advrayeItemID;
	public int advraygItemID;
	public int ingotIronDarkID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "RayGun";
		data.description = "A mod that adds in a raygun and advanced raygun which are very powerful.";
		data.authorList.add("Grim3212");
		data.authorList.add("Scokeev9");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Scokeev9 for the original mod.";
		data.logoFile = "/mods/logo.png";

		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			elementID = config.get(Configuration.CATEGORY_BLOCK, "Element Ore ID", 2655).getInt(2655);
			rayeItemID = config.get(Configuration.CATEGORY_ITEM, "Energy Canister ID", 9008).getInt(9008);
			elemID = config.get(Configuration.CATEGORY_ITEM, "Element 115 Item ID", 9009).getInt(9009);
			rayeeItemID = config.get(Configuration.CATEGORY_ITEM, "Empty Canister ID", 9010).getInt(9010);
			rayGItemID = config.get(Configuration.CATEGORY_ITEM, "Ray Gun ID", 9011).getInt(9011);
			advrayeeItemID = config.get(Configuration.CATEGORY_ITEM, "Empty Advanced Canister ID", 9012).getInt(9012);
			advrayeItemID = config.get(Configuration.CATEGORY_ITEM, "Advanced Energy Canister ID", 9013).getInt(9013);
			advraygItemID = config.get(Configuration.CATEGORY_ITEM, "Advanced Raygun ID", 9014).getInt(9014);
			ingotIronDarkID = config.get(Configuration.CATEGORY_ITEM, "Tainted Iron Ingot ID", 9015).getInt(9015);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Raygun has had a problem loading it's configuration");
		} finally {
			config.save();
		}

		if (FMLCommonHandler.instance().getSide().isClient()) {
			MinecraftForge.EVENT_BUS.register(new Sounds());
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		GameRegistry.registerWorldGenerator(new ElementGenerator());

		element = (new BlockElement(elementID, 0)).setHardness(2.5F).setResistance(30.0F).setLightValue(0.4F).setUnlocalizedName("element").setCreativeTab(CreativeTabs.tabBlock);
		rayeItem = (new RayItem(rayeItemID)).setUnlocalizedName("rayeItem").setCreativeTab(CreativeTabs.tabMaterials);
		elemItem = (new RayItem(elemID)).setUnlocalizedName("elemItem").setCreativeTab(CreativeTabs.tabMaterials);
		rayeeItem = (new RayItem(rayeeItemID)).setUnlocalizedName("rayeeItem").setCreativeTab(CreativeTabs.tabMaterials);
		raygItem = (new ItemRayg(rayGItemID)).setUnlocalizedName("raygItem").setCreativeTab(CreativeTabs.tabCombat);
		advrayeeItem = (new RayItem(advrayeeItemID)).setUnlocalizedName("advrayeeItem").setCreativeTab(CreativeTabs.tabMaterials);
		advrayeItem = (new RayItem(advrayeItemID)).setUnlocalizedName("advrayeItem").setCreativeTab(CreativeTabs.tabMaterials);
		advraygItem = (new ItemAdvRayg(advraygItemID)).setUnlocalizedName("advraygItem").setCreativeTab(CreativeTabs.tabCombat);
		ingotIronDark = (new RayItem(ingotIronDarkID)).setUnlocalizedName("ingotIronDark").setCreativeTab(CreativeTabs.tabMaterials);

		GameRegistry.registerBlock(element);
		LanguageRegistry.addName(element, "Element 115 Ore");
		LanguageRegistry.addName(rayeItem, "Energy Canister");
		LanguageRegistry.addName(elemItem, "Element 115");
		LanguageRegistry.addName(rayeeItem, "Empty Canister");
		LanguageRegistry.addName(raygItem, "Ray Gun");
		LanguageRegistry.addName(advrayeeItem, "Empty Advanced Canister");
		LanguageRegistry.addName(advrayeItem, "Advanced Energy Canister");
		LanguageRegistry.addName(advraygItem, "Advanced Raygun");
		LanguageRegistry.addName(ingotIronDark, "Tainted Iron Ingot");

		GameRegistry.addRecipe(new ItemStack(rayeItem, 1), new Object[] { "Y", "X", Character.valueOf('X'), rayeeItem, Character.valueOf('Y'), elemItem });
		GameRegistry.addRecipe(new ItemStack(rayeeItem, 2), new Object[] { "YXY", "Y Y", "YXY", Character.valueOf('X'), Item.ingotIron, Character.valueOf('Y'), Block.glass });
		GameRegistry.addRecipe(new ItemStack(raygItem, 1), new Object[] { "XZ ", " XY", " XX", Character.valueOf('X'), Item.ingotIron, Character.valueOf('Y'), elemItem, Character.valueOf('Z'), Item.redstone });
		GameRegistry.addRecipe(new ItemStack(advraygItem, 1), new Object[] { "XZ ", " XY", " XX", Character.valueOf('X'), ingotIronDark, Character.valueOf('Y'), raygItem, Character.valueOf('Z'), Item.redstone });
		GameRegistry.addRecipe(new ItemStack(advrayeeItem, 2), new Object[] { "YXY", "Y Y", "YXY", Character.valueOf('X'), ingotIronDark, Character.valueOf('Y'), Block.glass });
		GameRegistry.addRecipe(new ItemStack(advrayeItem, 1), new Object[] { "XY", "YY", Character.valueOf('X'), advrayeeItem, Character.valueOf('Y'), elemItem });
		GameRegistry.addRecipe(new ItemStack(ingotIronDark, 1), new Object[] { "XYX", Character.valueOf('X'), elemItem, Character.valueOf('Y'), Item.ingotIron });

		EntityRegistry.registerModEntity(EntityRayw.class, "RayShot", 2, this, 400, 20, true);
		EntityRegistry.registerModEntity(EntityAdvRayw.class, "AdvRayShot", 3, this, 400, 20, true);
	}

}
