// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode 

package grim3212.treasuremob;

import java.util.Map;

import net.minecraft.entity.EnumCreatureType;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

// Referenced classes of package net.minecraft.src:
//            BaseMod, EntityTreasureMob, RenderTreasureMob, ModelTreasureMob, 
//            ModLoader, EnumCreatureType
@Mod(modid = "TreasureMob", name = "Treasure Mob", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class TreasureMob
{
	@SidedProxy(clientSide = "grim3212.treasuremob.common.ClientProxy", serverSide = "grim3212.treasuremob.common.CommonProxy")
	public static grim3212.treasuremob.common.CommonProxy proxy;
	@Instance("TreasureMob")
	public static TreasureMob instance;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {

		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Treasure Mob";
		data.description = "Adds in a new mob that is kind of rare and drops a variety rare and common apart.";
		data.authorList.add("Grim3212");
		data.authorList.add("Chao");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Chao for the original mod.";
		data.logoFile = "/mods/logo.png";
		
	}
	
	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		
		LanguageRegistry.instance().addStringLocalization("entity.Treasure.name", "en_US", "Treasure Mob");
		
		EntityRegistry.registerGlobalEntityID(EntityTreasureMob.class, "Treasure", 87, 0xA47227, 0xFFFC00);
        EntityRegistry.addSpawn(EntityTreasureMob.class, 50, 0, 4, EnumCreatureType.creature);
    }
}
