package grim3212.mysticpack;

import java.util.Random;
import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.world.World;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "MysticRuins", name = "Mystic Ruins", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class MysticRuins {
	@SidedProxy(clientSide = "grim3212.mysticpack.common.ClientProxy", serverSide = "grim3212.mysticpack.common.CommonProxy")
	public static grim3212.mysticpack.common.CommonProxy proxy;
	@Instance("MysticRuins")
	public static MysticRuins instance;

	public static Block treasureIron;
	public static Block treasureGold;
	public static Block vines;
	public static Item vinesStrand;
	public Item bowlSoupBitter;

	public int bowlSoupBitterID;
	public int vinesID;
	public int vinesStrandID;
	public int treasureGoldID;
	public int treasureIronID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Mystic Ruins";
		data.description = "Adds in new ruins that generate underground that are full of awesome things to find.";
		data.authorList.add("Grim3212");
		data.authorList.add("Axebane");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Axebane for the original mod.";
		data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			bowlSoupBitterID = config.get(Configuration.CATEGORY_ITEM, "Bitter Soup ID", 9069).getInt(9069);
			vinesStrandID = config.get(Configuration.CATEGORY_ITEM, "Strand of Vine ID", 9070).getInt(9070);
			vinesID = config.get(Configuration.CATEGORY_BLOCK, "Vines Block ID", 2689).getInt(2689);
			treasureGoldID = config.get(Configuration.CATEGORY_BLOCK, "Treasure Chest Gold ID", 2690).getInt(2690);
			treasureIronID = config.get(Configuration.CATEGORY_BLOCK, "Treasure Chest Iron ID", 2691).getInt(2691);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Mystic Ruins has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		GameRegistry.registerWorldGenerator(new MysticRuinsGenerator());
		
		bowlSoupBitter = (new ItemSoupBitter(bowlSoupBitterID, 5)).setUnlocalizedName("bowlSoupBitter").setCreativeTab(MysticOres.customTab);
		vinesStrand = (new ItemVinesStrand(vinesStrandID)).setUnlocalizedName("vinesStrand").setCreativeTab(MysticOres.customTab);
		vines = (new BlockVines(vinesID, 0)).setHardness(0.1F).setResistance(5F).setUnlocalizedName("vines");
		treasureGold = (new BlockTreasureGold(treasureGoldID, 0)).setHardness(2.0F).setResistance(5F).setUnlocalizedName("treasureChest").setCreativeTab(MysticOres.customTab);
		treasureIron = (new BlockTreasureIron(treasureIronID, 0)).setHardness(2.0F).setResistance(5F).setUnlocalizedName("treasureIron").setCreativeTab(MysticOres.customTab);

		GameRegistry.registerBlock(treasureIron);
		GameRegistry.registerBlock(treasureGold);
		GameRegistry.registerBlock(vines);

		LanguageRegistry.addName(treasureIron, "Iron Treasure Chest");
		LanguageRegistry.addName(treasureGold, "Golden Treasure Chest");
		LanguageRegistry.addName(vines, "Vines");
		LanguageRegistry.addName(vinesStrand, "Strand of Vine");
		LanguageRegistry.addName(bowlSoupBitter, "Bitter Soup");

		GameRegistry.addRecipe(new ItemStack(Item.paper, 1), new Object[] { "XXX", 'X', vinesStrand });
		GameRegistry.addRecipe(new ItemStack(Item.silk, 1), new Object[] { "X", "X", "X", 'X', vinesStrand });
		GameRegistry.addRecipe(new ItemStack(Block.leaves, 1), new Object[] { "XX", "XX", 'X', vinesStrand });
		GameRegistry.addRecipe(new ItemStack(bowlSoupBitter, 1), new Object[] { "X", "X", "O", 'X', vinesStrand, 'O', Item.bowlEmpty });
		GameRegistry.addRecipe(new ItemStack(Block.ladder, 4), new Object[] { "X X", "XXX", "X X", 'X', vinesStrand });
	}
}
