// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode 

package grim3212.blackdiamond;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.EnumHelper;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "BlackDiamond", name = "Black Diamond", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class BlackDiamond {

	@SidedProxy(clientSide = "grim3212.blackdiamond.common.ClientProxy", serverSide = "grim3212.blackdiamond.common.CommonProxy")
	public static grim3212.blackdiamond.common.CommonProxy proxy;
	@Instance("BlackDiamond")
	public static BlackDiamond instance;
	
	public int deskItemID;
	public int deskPickID;
	public int deskSpadeID;
	public int deskAxeID;
	public int deskSwordID;
	public int deskHoeID;
	public int blHelmID;
	public int blPlateID;
	public int blLegID;
	public int blBootsID;
	public int whiteItemID;
	public int blackBlockID;
	public int blackOreID;
	
	public static Item deskItem;
	public static Item deskPick;
	public static Item deskShovel;
	public static Item deskAxe;
	public static Item deskHoe;
	public static Item deskSword;
	public static Item blackHelmet;
	public static Item blackPlate;
	public static Item blackLeggings;
	public static Item blackBoots;
	public static Block blackBlock;
	public static Block BlackOre;
	public static Item whiteItem;

	static EnumToolMaterial blackdiamond = EnumHelper.addToolMaterial("blackdiamond", 3, 3122, 15F, 3, 20);
	static EnumArmorMaterial blackarmor = EnumHelper.addArmorMaterial("blackarmor", 35, new int[] { 3, 8, 6, 3 }, 20);

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Black Diamond";
    	data.description = "A mod that adds in a new ore which is black diamond and allows you to craft new set of armor, tools, and weapons with black diamond.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Tingelz");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Tingelz for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			deskItemID = config.get(Configuration.CATEGORY_ITEM, "Black Diamond ID", 9018).getInt(9018);
			deskPickID = config.get(Configuration.CATEGORY_ITEM, "Black Pickaxe ID", 9019).getInt(9019);
			deskSpadeID = config.get(Configuration.CATEGORY_ITEM, "Black Spade ID", 9020).getInt(9020);
			deskAxeID = config.get(Configuration.CATEGORY_ITEM, "Black Axe ID", 9021).getInt(9021);
			deskSwordID = config.get(Configuration.CATEGORY_ITEM, "Black Sword ID", 9022).getInt(9022);
			deskHoeID = config.get(Configuration.CATEGORY_ITEM, "Black Hoe ID", 9023).getInt(9023);
			blHelmID = config.get(Configuration.CATEGORY_ITEM, "Black Helmet ID", 9024).getInt(9024);
			blPlateID = config.get(Configuration.CATEGORY_ITEM, "Black ChestPlate ID", 9025).getInt(9025);
			blLegID = config.get(Configuration.CATEGORY_ITEM, "Black Leggings ID", 9026).getInt(9026);
			blBootsID = config.get(Configuration.CATEGORY_ITEM, "Black Boots ID", 9027).getInt(9027);
			whiteItemID = config.get(Configuration.CATEGORY_ITEM, "White Diamond ID", 9028).getInt(9028);
			blackBlockID = config.get(Configuration.CATEGORY_BLOCK, "Black Block of Diamond ID", 2658).getInt(2658);
			blackOreID = config.get(Configuration.CATEGORY_BLOCK, "Black Diamond Ore ID", 2659).getInt(2659);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Black Diamond has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		GameRegistry.registerWorldGenerator(new BlackGenerator());

		whiteItem = (new BlackGeneric(whiteItemID)).setUnlocalizedName("whiteItem").setCreativeTab(CreativeTabs.tabMisc);;
		BlackOre = (new BlackOre(blackOreID, 0)).setHardness(2.0F).setResistance(5F).setUnlocalizedName("BlackOre");
		blackBlock = (new BlockBlack(blackBlockID, 0)).setHardness(2.0F).setResistance(5F).setUnlocalizedName("blackBlock");
		blackBoots = (new BlackArmor(blBootsID, blackarmor, 4, 3)).setUnlocalizedName("blackBoots").setCreativeTab(CreativeTabs.tabCombat);
		blackLeggings = (new BlackArmor(blLegID, blackarmor, 4, 2)).setUnlocalizedName("blackLeggings").setCreativeTab(CreativeTabs.tabCombat);
		blackPlate = (new BlackArmor(blPlateID, blackarmor, 4, 1)).setUnlocalizedName("blackPlate").setCreativeTab(CreativeTabs.tabCombat);
		blackHelmet = (new BlackArmor(blHelmID, blackarmor, 4, 0)).setUnlocalizedName("blackHelmet").setCreativeTab(CreativeTabs.tabCombat);
		deskSword = (new BlackSword(deskSwordID, blackdiamond)).setUnlocalizedName("deskSword");
		deskHoe = (new BlackHoe(deskHoeID, blackdiamond)).setUnlocalizedName("deskHoe");
		deskAxe = (new BlackAxe(deskAxeID, blackdiamond)).setUnlocalizedName("deskAxe");
		deskShovel = (new BlackSpade(deskSpadeID, blackdiamond)).setUnlocalizedName("deskShovel");
		deskPick = (new BlackPickaxe(deskPickID, blackdiamond)).setUnlocalizedName("deskPick");
		deskItem = (new BlackGeneric(deskItemID)).setUnlocalizedName("deskItem").setCreativeTab(CreativeTabs.tabMisc);

		LanguageRegistry.addName(deskPick, "Black Pickaxe");
		GameRegistry.addRecipe(new ItemStack(deskPick, 1), new Object[] { "###", " X ", " X ", Character.valueOf('X'), Item.stick, Character.valueOf('#'), deskItem });
		LanguageRegistry.addName(deskSword, "Black Sword");
		GameRegistry.addRecipe(new ItemStack(deskSword, 1), new Object[] { "#", "#", "X", Character.valueOf('X'), Item.stick, Character.valueOf('#'), deskItem });
		LanguageRegistry.addName(deskAxe, "Black Axe");
		GameRegistry.addRecipe(new ItemStack(deskAxe, 1), new Object[] { "## ", "#X ", " X ", Character.valueOf('X'), Item.stick, Character.valueOf('#'), deskItem });
		LanguageRegistry.addName(deskHoe, "Black Hoe");
		GameRegistry.addRecipe(new ItemStack(deskHoe, 1), new Object[] { "## ", " X ", " X ", Character.valueOf('X'), Item.stick, Character.valueOf('#'), deskItem });
		LanguageRegistry.addName(blackHelmet, "Black Helmet");
		GameRegistry.addRecipe(new ItemStack(blackHelmet, 1), new Object[] { "###", "# #", Character.valueOf('#'), deskItem });
		LanguageRegistry.addName(blackPlate, "Black Plate");
		GameRegistry.addRecipe(new ItemStack(blackPlate, 1), new Object[] { "# #", "###", "###", Character.valueOf('#'), deskItem });
		LanguageRegistry.addName(blackLeggings, "Black Leggings");
		GameRegistry.addRecipe(new ItemStack(blackLeggings, 1), new Object[] { "###", "# #", "# #", Character.valueOf('#'), deskItem });
		LanguageRegistry.addName(blackBoots, "Black Boots");
		GameRegistry.addRecipe(new ItemStack(blackBoots, 1), new Object[] { "# #", "# #", Character.valueOf('#'), deskItem });

		GameRegistry.registerBlock(blackBlock, "BlackBlock");
		LanguageRegistry.addName(blackBlock, "Black Block of Diamond");
		GameRegistry.addRecipe(new ItemStack(blackBlock, 1), new Object[] { "###", "###", "###", Character.valueOf('#'), deskItem });
		GameRegistry.addRecipe(new ItemStack(deskItem, 9), new Object[] { "#", Character.valueOf('#'), blackBlock });
		GameRegistry.registerBlock(BlackOre, "BlackOre");
		LanguageRegistry.addName(BlackOre, "Black Diamond Ore");
		LanguageRegistry.addName(whiteItem, "White Diamond");
		GameRegistry.addRecipe(new ItemStack(whiteItem, 1), new Object[] { " X ", "XXX", " X ", Character.valueOf('X'), deskItem });
		LanguageRegistry.addName(deskItem, "Black Diamond");
		GameRegistry.addRecipe(new ItemStack(deskItem, 1), new Object[] { " X ", "X#X", " X ", Character.valueOf('X'), Block.obsidian, Character.valueOf('#'), Item.diamond });
		GameRegistry.addSmelting(BlackOre.blockID, new ItemStack(deskItem, 1), 0);
		LanguageRegistry.addName(deskShovel, "Black Shovel");
		GameRegistry.addRecipe(new ItemStack(deskShovel, 1), new Object[] { "#", "X", "X", Character.valueOf('X'), Item.stick, Character.valueOf('#'), deskItem });
	}

	
}
