package grim3212.calendar;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Calendar", name = "Calendar", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Calendar
{
	
    public static Block calendarBlock;
    public static Item calendarItem;
    public int calendarBlockID;
    public int calendarItemID;
    
    @SidedProxy(clientSide = "grim3212.calendar.common.ClientProxy", serverSide = "grim3212.calendar.common.CommonProxy")
	public static grim3212.calendar.common.CommonProxy proxy;
	@Instance("Calendar")
	public static Calendar instance;
    
	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Calendar";
    	data.description = "A mod that adds in a new block that allows you to see how long you have been playing on a specific world in Days, Months, and Years.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("voodoofrog");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to voodoofrog for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			calendarItemID = config.get(Configuration.CATEGORY_ITEM, "Calendar Item ID", 9031).getInt(9031);
			calendarBlockID = config.get(Configuration.CATEGORY_BLOCK, "Calendar Block ID", 2660).getInt(2660);
			
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Calendar has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

    @Init
    public void init(FMLInitializationEvent event)
    {
    	proxy.registerRenderInformation();
    	
    	calendarItem = (new ItemCalendar(calendarItemID)).setUnlocalizedName("calendarItem");
        calendarBlock = (new BlockCalendar(calendarBlockID, 0, net.minecraft.tileentity.TileEntity.class)).setHardness(1.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("calendarBlock");
    	
        GameRegistry.registerBlock(calendarBlock);
        TileEntityCalendarRenderer tileentitycalendarrenderer = new TileEntityCalendarRenderer();
        GameRegistry.registerTileEntity(TileEntityCalendar.class, "Calendar");
        ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCalendar.class, new TileEntityCalendarRenderer());
        LanguageRegistry.addName(calendarItem, "Calendar");
        GameRegistry.addRecipe(new ItemStack(calendarItem, 1), new Object[]
                {
                    "## ", "## ", "## ", Character.valueOf('#'), Item.paper
                });
        GameRegistry.addRecipe(new ItemStack(calendarItem, 1), new Object[]
                {
                    " ##", " ##", " ##", Character.valueOf('#'), Item.paper
                });
    }
}
