package grim3212.randomite;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Randomite", name = "Randomite", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Randomite {

	@SidedProxy(clientSide = "grim3212.randomite.common.ClientProxy", serverSide = "grim3212.randomite.common.CommonProxy")
	public static grim3212.randomite.common.CommonProxy proxy;
	@Instance("Randomite")
	public static Randomite instance;

	public static Block randomite;
	public int randomiteID;
	
	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Randomite";
    	data.description = "A mod that adds in a new ore that when you break it drops a random ore or an egg.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Scokeev9");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Scokeev9 for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			randomiteID = config.get(Configuration.CATEGORY_BLOCK, "Randomite ID", 2654).getInt(2654);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Randomite has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		GameRegistry.registerWorldGenerator(new RandomiteGenerator());

		randomite = (new BlockRandomite(randomiteID, 0)).setHardness(1.6F).setResistance(1.0F).setUnlocalizedName("randomite").setCreativeTab(CreativeTabs.tabBlock);

		GameRegistry.registerBlock(randomite);
		LanguageRegistry.addName(randomite, "Randomite");
	}

}
