// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode 

package grim3212.flatbedrock;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;

// Referenced classes of package net.minecraft.src:
//            BaseMod, World, Block

@Mod(modid = "FlatBedrock", name = "Flat Bedrock", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class FlatBedrock
{
	
	@SidedProxy(clientSide = "grim3212.flatbedrock.common.ClientProxy", serverSide = "grim3212.flatbedrock.common.CommonProxy")
	public static grim3212.flatbedrock.common.CommonProxy proxy;
	
	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Flat Bedrock";
    	data.description = "A mod that transforms the bedrock generatino to just a flat layer of bedrock on the last layer.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("grn_dog_72");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to grn_dog_72 for the original mod.";
    	data.logoFile = "/mods/logo.png";
	}
	
	@Init
	public void load(FMLInitializationEvent event) {
		
		proxy.registerRenderInformation();
		GameRegistry.registerWorldGenerator(new FlatGenerator());
	}
}
