// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode 

package grim3212.soda;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.block.BlockFlower;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

// Referenced classes of package net.minecraft.src:
//            BaseMod, ModLoader, Item, ItemStack, 
//            mod_carbonatedwater, ItemAppleSoda
@Mod(modid = "Soda", name = "Soda", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Soda {
	@SidedProxy(clientSide = "grim3212.soda.common.ClientProxy", serverSide = "grim3212.soda.common.CommonProxy")
	public static grim3212.soda.common.CommonProxy proxy;
	@Instance("Soda")
	public static Soda instance;

	public static Item sodaBottle;
	public int sodaID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Soda";
		data.description = "Adds in a bunch of different sodas that regenerate health.";
		data.authorList.add("Grim3212");
		data.authorList.add("Leesgowest");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Leesgowest for the original mod.";
		data.logoFile = "/mods/logo.png";

		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			sodaID = config.get(Configuration.CATEGORY_ITEM, "Soda ID", 9163).getInt(9163);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Soda has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();

		sodaBottle = (new ItemSodaBottle(sodaID)).setUnlocalizedName("sodabottle");

		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 0), new Object[] { "X", "Y", Character.valueOf('X'), Item.appleRed, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 5), new Object[] { "X", "Y", Character.valueOf('X'), Block.pumpkinLantern, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 1), new Object[] { " X ", "X X", "XXX", Character.valueOf('X'), Block.thinGlass });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 2), new Object[] { "X", "Y", Character.valueOf('X'), Item.slimeBall, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 6), new Object[] { "X", "Y", Character.valueOf('X'), Item.seeds, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 9), new Object[] { "X", "Y", Character.valueOf('X'), Block.pumpkin, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 12), new Object[] { "X", "Y", Character.valueOf('X'), BlockFlower.mushroomRed, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 4), new Object[] { "X", "Y", Character.valueOf('X'), Item.appleGold, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 8), new Object[] { "X", "Y", Character.valueOf('X'), Item.diamond, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 7), new Object[] { "X", "Y", Character.valueOf('X'), Item.bucketMilk, Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 9) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 10), new Object[] { "X", "Y", Character.valueOf('X'), new ItemStack(Item.dyePowder, 1, 3), Character.valueOf('Y'), new ItemStack(sodaBottle, 1, 11) });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 3), new Object[] { " X ", "X0X", " X ", Character.valueOf('X'), Item.ingotIron, Character.valueOf('0'), Item.flint });
		GameRegistry.addRecipe(new ItemStack(sodaBottle, 1, 11), new Object[] { "X", "Y", "Z", Character.valueOf('X'), new ItemStack(sodaBottle, 1, 3), Character.valueOf('Y'), Item.bucketWater, Character.valueOf('Z'), new ItemStack(sodaBottle, 1, 1) });

		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 0), "Apple Soda");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 1), "Soda Bottle");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 2), "Slurm");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 3), "Co2");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 4), "Golden Apple Soda");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 5), "Spiked Orange Soda");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 6), "Root Beer");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 7), "Orange Cream Soda");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 8), "Diamond Soda");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 9), "Orange Soda");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 10), "Cocoa Soda");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 11), "Carbonated Water");
		LanguageRegistry.addName(new ItemStack(sodaBottle, 1, 12), "Mushroom Soda");
	}
}
