package grim3212.corruption;

import java.util.Random;
import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.world.World;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Corruption", name = "Corruption", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Corruption {

	@SidedProxy(clientSide = "grim3212.corruption.common.ClientProxy", serverSide = "grim3212.corruption.common.CommonProxy")
	public static grim3212.corruption.common.CommonProxy proxy;
	@Instance("Corruption")
	public static Corruption instance;

	public static Block CorruptionBlock;
	public int corruptionID;
	
	public static boolean fire;
	public static boolean corruption;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Corruption";
    	data.description = "Adds in a new block that corrupts the blocks that surround it.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Nandonalt");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Nandonalt for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			corruptionID = config.get(Configuration.CATEGORY_BLOCK, "Corruption Block ID", 2726).getInt(2726);
			fire = config.get(Configuration.CATEGORY_GENERAL, "Enable Fire", true).getBoolean(true);
			corruption = config.get(Configuration.CATEGORY_GENERAL, "Enable Corruption", true).getBoolean(true);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Corruption Block has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		GameRegistry.registerWorldGenerator(new CorruptionGenerator());
		
		CorruptionBlock = (new CorruptionBlock(corruptionID, 0)).setHardness(1.0F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("BlockCorruption").setCreativeTab(CreativeTabs.tabMaterials);

		LanguageRegistry.addName(CorruptionBlock, "Corruption Block");
		GameRegistry.registerBlock(CorruptionBlock);
	}

}
