package grim3212.wallclock;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemReed;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "WallClock", name = "Wall Clock", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class WallClock {
	@SidedProxy(clientSide = "grim3212.wallclock.common.ClientProxy", serverSide = "grim3212.wallclock.common.CommonProxy")
	public static grim3212.wallclock.common.CommonProxy proxy;
	@Instance("WallClock")
	public static WallClock instance;

	public static int wallclocktext;
	public static Block WallClock;
	public static Item WallClockItem;

	public int wallClockBlockID;
	public int wallClockItemID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Wall Clock";
		data.description = "Adds in a placeable wall clock.";
		data.authorList.add("Grim3212");
		data.authorList.add("Nandonalt");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Nandonalt for the original mod.";
		data.logoFile = "/mods/logo.png";

		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			wallClockBlockID = config.get(Configuration.CATEGORY_BLOCK, "Wall Clock Block ID", 2727).getInt(2727);
			wallClockItemID = config.get(Configuration.CATEGORY_ITEM, "Wall Clock Item ID", 9122).getInt(9122);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Wall Clock has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();

		WallClock = new BlockWallClock(wallClockBlockID, wallclocktext).setHardness(0.75F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("WallClockBlock");
		WallClockItem = new ItemClock(wallClockItemID, WallClock).setUnlocalizedName("wallclockitem").setCreativeTab(CreativeTabs.tabDecorations);

		GameRegistry.registerBlock(WallClock);
		LanguageRegistry.addName(WallClockItem, "Wall Clock");
		AddRecipes();
	}

	public void AddRecipes() {
		GameRegistry.addRecipe(new ItemStack(WallClockItem, 1), new Object[] { "XIX", "IRI", "XIX", Character.valueOf('X'), Block.blocksList[5], Character.valueOf('I'), Item.itemsList[266], Character.valueOf('R'), Item.itemsList[331] });
		GameRegistry.addRecipe(new ItemStack(WallClockItem, 1), new Object[] { "XXX", "XRX", "XXX", Character.valueOf('X'), Block.blocksList[5], Character.valueOf('R'), Item.itemsList[347] });
		GameRegistry.addShapelessRecipe(new ItemStack(Item.itemsList[347], 1), new Object[] { new ItemStack(WallClockItem) });
	}
}
