package grim3212.cactuscraft;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemHoe;
import net.minecraft.item.ItemPickaxe;
import net.minecraft.item.ItemSpade;
import net.minecraft.item.ItemStack;
import net.minecraft.item.ItemSword;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "CactusCraft", name = "Cactus Craft", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class CactusCraft {

	@SidedProxy(clientSide = "grim3212.cactuscraft.common.ClientProxy", serverSide = "grim3212.cactuscraft.common.CommonProxy")
	public static grim3212.cactuscraft.common.CommonProxy proxy;
	@Instance("CactusCraft")
	public static CactusCraft instance;
	
	public int cactusStickID;
	public int cactusPickID;
	public int cactusAxeID;
	public int cactusSwordID;
	public int cactusHoeID;
	public int cactusSpadeID;

	public static Item CactusStick;
	public static Item CactusPickaxe;
	public static Item CactusAxe;
	public static Item CactusSword;
	public static Item CactusHoe;
	public static Item CactusSpade;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Cactus Craft";
    	data.description = "Adds in a bunch of cactus oriented tools.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Nandonalt");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Nandonalt for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			cactusStickID = config.get(Configuration.CATEGORY_ITEM, "Cactus Stick ID", 9124).getInt(9124);
			cactusPickID = config.get(Configuration.CATEGORY_ITEM, "Cactus Pickaxe ID", 9125).getInt(9124);
			cactusAxeID = config.get(Configuration.CATEGORY_ITEM, "Cactus Axe ID", 9126).getInt(9126);
			cactusSwordID = config.get(Configuration.CATEGORY_ITEM, "Cactus Sword ID", 9127).getInt(9127);
			cactusHoeID = config.get(Configuration.CATEGORY_ITEM, "Cactus Hoe ID", 9128).getInt(9128);
			cactusSpadeID = config.get(Configuration.CATEGORY_ITEM, "Cactus Spade ID", 9129).getInt(9129);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Cactus Craft has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		
		CactusSpade = (new CactusSpade(cactusSpadeID, EnumToolMaterial.WOOD)).setUnlocalizedName("CSpade").setCreativeTab(CreativeTabs.tabTools);
		CactusHoe = (new CactusHoe(cactusHoeID, EnumToolMaterial.WOOD)).setUnlocalizedName("CHoe").setCreativeTab(CreativeTabs.tabTools);
		CactusSword = (new CactusSword(cactusSwordID, EnumToolMaterial.STONE)).setUnlocalizedName("CSword").setCreativeTab(CreativeTabs.tabCombat);
		CactusAxe = (new CactusAxe(cactusAxeID, EnumToolMaterial.STONE)).setUnlocalizedName("CAxe").setCreativeTab(CreativeTabs.tabTools);
		CactusPickaxe = (new CactusPickaxe(cactusPickID, EnumToolMaterial.WOOD)).setUnlocalizedName("CPick").setCreativeTab(CreativeTabs.tabTools);
		CactusStick = (new CactusItem(cactusStickID)).setUnlocalizedName("CStick").setCreativeTab(CreativeTabs.tabMaterials);
		
		LanguageRegistry.addName(CactusStick, "Cactus Stick");
		LanguageRegistry.addName(CactusPickaxe, "Cactus Pickaxe");
		LanguageRegistry.addName(CactusAxe, "Cactus Axe");
		LanguageRegistry.addName(CactusSword, "Cactus Sword");
		LanguageRegistry.addName(CactusHoe, "Cactus Hoe");
		LanguageRegistry.addName(CactusSpade, "Cactus Spade");
		this.AddRecipes();
	}

	public void AddRecipes() {
		GameRegistry.addRecipe(new ItemStack(CactusStick, 2), new Object[] { "B", "B", Character.valueOf('B'), Item.itemsList[81] });
		GameRegistry.addRecipe(new ItemStack(CactusPickaxe, 1), new Object[] { "BBB", " I ", " I ", Character.valueOf('B'), Block.blocksList[81], Character.valueOf('I'), CactusStick });
		GameRegistry.addRecipe(new ItemStack(CactusAxe, 1), new Object[] { "BB ", "BI ", " I ", Character.valueOf('B'), Block.blocksList[81], Character.valueOf('I'), CactusStick });
		GameRegistry.addRecipe(new ItemStack(CactusSpade, 1), new Object[] { " B ", " I ", " I ", Character.valueOf('B'), Block.blocksList[81], Character.valueOf('I'), CactusStick });
		GameRegistry.addRecipe(new ItemStack(CactusHoe, 1), new Object[] { "BB ", " I ", " I ", Character.valueOf('B'), Block.blocksList[81], Character.valueOf('I'), CactusStick });
		GameRegistry.addRecipe(new ItemStack(CactusSword, 1), new Object[] { " B ", " B ", " I ", Character.valueOf('B'), Block.blocksList[81], Character.valueOf('I'), CactusStick });
		GameRegistry.addRecipe(new ItemStack(Block.blocksList[58], 1), new Object[] { "BB", "BB", Character.valueOf('B'), Block.blocksList[81] });
		GameRegistry.addRecipe(new ItemStack(Block.blocksList[50], 2), new Object[] { "0", "I", Character.valueOf('0'), Item.itemsList[263], Character.valueOf('I'), CactusStick });
		GameRegistry.addSmelting(CactusStick.itemID, new ItemStack(Item.itemsList[280]), 0);
	}
}
