package grim3212.slingshot;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Slingshot", name = "Slingshot", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class Slingshot
{
	@SidedProxy(clientSide = "grim3212.slingshot.common.ClientProxy", serverSide = "grim3212.slingshot.common.CommonProxy")
	public static grim3212.slingshot.common.CommonProxy proxy;
	@Instance("Slingshot")
	public static Slingshot instance;
	
    public static Item Slingshot;
    public static Item Slingpellet;
    
    public int slingshotID;
    public static int slingpelletID;

    
    @PreInit
	public void preInit(FMLPreInitializationEvent event) {
    	
    	ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Slingshot";
    	data.description = "A mod that adds a slingshot and pellets to shoot at those pesky mobs.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Blocker226");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Blocker226 for the original mod.";
    	data.logoFile = "/mods/logo.png";
    	
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			slingshotID = config.get(Configuration.CATEGORY_ITEM, "SlingShot ID", 9066).getInt(9066);
			slingpelletID = config.get(Configuration.CATEGORY_ITEM, "SlingPellet ID", 9067).getInt(9067);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Slingshot has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}
    
    @Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
    	Slingshot = (new ItemSlingshot(slingshotID)).setUnlocalizedName("Slingshot").setCreativeTab(CreativeTabs.tabCombat);
    	Slingpellet = (new ItemSlingpellet(slingpelletID)).setUnlocalizedName("Slingshot Pellet").setCreativeTab(CreativeTabs.tabCombat);
    	
        LanguageRegistry.addName(Slingshot, "Slingshot");
        LanguageRegistry.addName(Slingpellet, "Slingshot Pellet");
        GameRegistry.addRecipe(new ItemStack(Slingshot, 1), new Object[] {"#@#", " # ", " # ", Character.valueOf('#'), Item.stick, Character.valueOf('@'), Item.silk});
        GameRegistry.addRecipe(new ItemStack(Slingpellet, 2), new Object[] {"#", Character.valueOf('#'), Block.dirt});
        GameRegistry.addRecipe(new ItemStack(Slingpellet, 2), new Object[] {"#", Character.valueOf('#'), Block.cobblestone});
        GameRegistry.addRecipe(new ItemStack(Slingpellet, 4), new Object[] {"#", Character.valueOf('#'), Block.stone});
        EntityRegistry.registerModEntity(EntitySlingpellet.class, "SlingPellet", 2, this, 400, 20, true);
    }
}
