package grim3212.pokeball;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Pokeball", name = "Pokeball", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Pokeball {

	@SidedProxy(clientSide = "grim3212.pokeball.common.ClientProxy", serverSide = "grim3212.pokeball.common.CommonProxy")
	public static grim3212.pokeball.common.CommonProxy proxy;
	@Instance("Pokeball")
	public static Pokeball instance;

	public int pokeballID;
	public static Item pokeball;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Pokeball";
    	data.description = "Adds in a new item that allows you to catch and release any mobs... (I think it works with mods)";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Apox159");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Apox159 for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			pokeballID = config.get(Configuration.CATEGORY_ITEM, "Pokeball ID", 9065).getInt(9065);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Pokeball has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();

		pokeball = (new ItemPokeball(pokeballID)).setUnlocalizedName("Pokeball");

		LanguageRegistry.addName(pokeball, "Pokeball");
		GameRegistry.addRecipe(new ItemStack(pokeball), new Object[] { "RRR", "CBC", "III", Character.valueOf('R'), Item.redstone, Character.valueOf('C'), Item.coal, Character.valueOf('B'), Block.stoneButton, Character.valueOf('I'), Item.ingotIron });

		EntityRegistry.registerModEntity(EntityPokeball.class, "Pokeball", 6, this, 400, 20, true);

	}

}
