// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode 

package grim3212.nuclearcraft;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.EnumHelper;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "NuclearCraft", name = "NuclearCraft", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class NuclearCraft {
	@SidedProxy(clientSide = "grim3212.nuclearcraft.common.ClientProxy", serverSide = "grim3212.nuclearcraft.common.CommonProxy")
	public static grim3212.nuclearcraft.common.CommonProxy proxy;
	@Instance("NuclearCraft")
	public static NuclearCraft instance;
	
	public static Block nuclear_bomb;
	public static Block uranium_ore;
	public static Item uranium_ingot;
	public static Item refined_uranium;
	public static Item plutonium_ingot;
	public static Item refined_plutonium;
	public static Item graphite;
	public static Item graphite_rod;
	public static Item reactor_core;
	public static Item reactor_core_case;
	public static Item iron_parts;
	public static Block reactor;
	public static Block aluminium;
	public static Block bomb_shell;
	public static Block c4;
	public static Item rs_helmet;
	public static Item rs_chest;
	public static Item rs_legs;
	public static Item rs_boots;
	
	public int nuclearBombID;
	public int uraniumOreID;
	public int uraniumIngotID;
	public int refinedUraniumID;
	public int plutoniumIngotID;
	public int refinedPlutoniumID;
	public int graphiteID;
	public int graphiteRodID;
	public int reactorCoreID;
	public int reactorCoreCaseID;
	public int ironPartsID;
	public int reactorID;
	public int aluminumID;
	public int bombShellID;
	public int c4ID;
	public int rsHelmID;
	public int rsChestID;
	public int rsLegsID;
	public int rsBootsID;
	
	static EnumArmorMaterial antiRadiation = EnumHelper.addArmorMaterial("antiRadiation", 5, new int[] { 2, 5, 3, 1 }, 15);
	

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Nuclear Craft";
		data.description = "Adds in a bunch of new items and blocks around nuclear bombs.  HAVE FUN :D";
		data.authorList.add("Grim3212");
		data.authorList.add("nosedive42");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to nosedive42 for the original mod.";
		data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			uraniumIngotID = config.get(Configuration.CATEGORY_ITEM, "Uranium Ingot ID", 9052).getInt(9052);
			refinedUraniumID = config.get(Configuration.CATEGORY_ITEM, "Refined Uranium ID", 9053).getInt(9053);
			plutoniumIngotID = config.get(Configuration.CATEGORY_ITEM, "Plutonium Ingot ID", 9054).getInt(9054);
			refinedPlutoniumID = config.get(Configuration.CATEGORY_ITEM, "Refined Plutonium ID", 9055).getInt(9055);
			graphiteID = config.get(Configuration.CATEGORY_ITEM, "Graphite ID", 9056).getInt(9056);
			graphiteRodID = config.get(Configuration.CATEGORY_ITEM, "Graphite Rod ID", 9057).getInt(9057);
			reactorCoreID = config.get(Configuration.CATEGORY_ITEM, "Reactor Core ID", 9058).getInt(9058);
			reactorCoreCaseID = config.get(Configuration.CATEGORY_ITEM, "Reactor Core Case ID", 9059).getInt(9059);
			ironPartsID = config.get(Configuration.CATEGORY_ITEM, "Iron Parts ID", 9060).getInt(9060);
			rsHelmID = config.get(Configuration.CATEGORY_ITEM, "AntiRadiation Helmet ID", 9061).getInt(9061);
			rsChestID = config.get(Configuration.CATEGORY_ITEM, "AntiRadiation Chestplate ID", 9062).getInt(9062);
			rsLegsID = config.get(Configuration.CATEGORY_ITEM, "AntiRadiation Leggings ID", 9063).getInt(9063);
			rsBootsID = config.get(Configuration.CATEGORY_ITEM, "AntiRadiation Boots ID", 9064).getInt(9064);
			
			nuclearBombID = config.get(Configuration.CATEGORY_BLOCK, "Nuclear Bomb ID", 2681).getInt(2681);
			uraniumOreID = config.get(Configuration.CATEGORY_BLOCK, "Uranium Ore ID", 2682).getInt(2682);
			reactorID = config.get(Configuration.CATEGORY_BLOCK, "Reactor ID", 2683).getInt(2683);
			c4ID = config.get(Configuration.CATEGORY_BLOCK, "C4 ID", 2684).getInt(2684);
			aluminumID = config.get(Configuration.CATEGORY_BLOCK, "Aluminum ID", 2685).getInt(2685);
			bombShellID = config.get(Configuration.CATEGORY_BLOCK, "BombShell ID", 2686).getInt(2686);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "NuclearCraft has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		GameRegistry.registerWorldGenerator(new NuclearGenerator());
		
		nuclear_bomb = (new NC_BlockNuclearBomb(nuclearBombID, 8, 7)).setHardness(1.0F).setStepSound(Block.soundMetalFootstep).setCreativeTab(CreativeTabs.tabRedstone);
		reactor = (new NC_BlockNuclearReactor(reactorID, 10)).setHardness(1.0F).setStepSound(Block.soundMetalFootstep).setCreativeTab(CreativeTabs.tabDecorations);
		aluminium = (new NC_BlockAluminum(aluminumID, 0)).setHardness(1.0F).setStepSound(Block.soundMetalFootstep).setCreativeTab(CreativeTabs.tabDecorations);
		bomb_shell = (new NC_BlockBombShell(bombShellID, 1)).setHardness(1.0F).setStepSound(Block.soundMetalFootstep).setCreativeTab(CreativeTabs.tabDecorations);
		c4 = (new NC_BlockC4(c4ID, 3, 2)).setHardness(1.0F).setStepSound(Block.soundMetalFootstep).setCreativeTab(CreativeTabs.tabRedstone);
		uranium_ore = (new NC_BlockUraniumOre(uraniumOreID, 16)).setHardness(1.0F).setStepSound(Block.soundStoneFootstep).setLightValue(0.55F).setCreativeTab(CreativeTabs.tabDecorations);
		
		rs_boots = (new NC_Armor(rsBootsID, antiRadiation, 3, 3)).setUnlocalizedName("rs_boots").setCreativeTab(CreativeTabs.tabCombat);
		rs_legs = (new NC_Armor(rsLegsID, antiRadiation, 3, 2)).setUnlocalizedName("rs_legs").setCreativeTab(CreativeTabs.tabCombat);
		rs_chest = (new NC_Armor(rsChestID, antiRadiation, 3, 1)).setUnlocalizedName("rs_chest").setCreativeTab(CreativeTabs.tabCombat);
		rs_helmet = (new NC_Armor(rsHelmID, antiRadiation, 3, 0)).setUnlocalizedName("rs_helmet").setCreativeTab(CreativeTabs.tabCombat);
		
		iron_parts = (new NC_GenericItem(ironPartsID)).setUnlocalizedName("Iron Parts").setCreativeTab(CreativeTabs.tabMaterials);
		reactor_core_case = (new NC_GenericItem(reactorCoreCaseID)).setUnlocalizedName("Reactor Core Case").setCreativeTab(CreativeTabs.tabMaterials);
		reactor_core = (new NC_GenericItem(reactorCoreID)).setUnlocalizedName("Nuclear Reactor Core").setCreativeTab(CreativeTabs.tabMaterials);
		graphite_rod = (new NC_GenericItem(graphiteRodID)).setUnlocalizedName("Graphite Rod").setCreativeTab(CreativeTabs.tabMaterials);
		graphite = (new NC_GenericItem(graphiteID)).setUnlocalizedName("Graphite").setCreativeTab(CreativeTabs.tabMaterials);
		refined_plutonium = (new NC_GenericItem(refinedPlutoniumID)).setUnlocalizedName("Refined Plutonium").setCreativeTab(CreativeTabs.tabMaterials);
		plutonium_ingot = (new NC_GenericItem(plutoniumIngotID)).setUnlocalizedName("Plutonium Ingot").setCreativeTab(CreativeTabs.tabMaterials);
		refined_uranium = (new NC_GenericItem(refinedUraniumID)).setUnlocalizedName("Refined Uranium").setCreativeTab(CreativeTabs.tabMaterials);
		uranium_ingot = (new NC_GenericItem(uraniumIngotID)).setUnlocalizedName("Uranium Ingot").setCreativeTab(CreativeTabs.tabMaterials);
		
		GameRegistry.registerBlock(uranium_ore);
		GameRegistry.addRecipe(new ItemStack(uranium_ore, 1), new Object[] { "RDR", "DGD", "RDR", Character.valueOf('R'), Item.redstone, Character.valueOf('G'), Block.glowStone, Character.valueOf('D'), Item.diamond });
		uranium_ore.setUnlocalizedName("Uranium Ore");
		LanguageRegistry.addName(uranium_ore, "Uranium Ore");
		LanguageRegistry.addName(uranium_ingot, "Uranium Ingot");
		GameRegistry.addSmelting(uranium_ore.blockID, new ItemStack(uranium_ingot), 0);
		LanguageRegistry.addName(refined_uranium, "Refined Uranium");
		GameRegistry.addRecipe(new ItemStack(refined_uranium, 1), new Object[] { " U ", "U U", Character.valueOf('U'), uranium_ingot });
		LanguageRegistry.addName(plutonium_ingot, "Plutonium Ingot");
		GameRegistry.addRecipe(new ItemStack(plutonium_ingot, 1), new Object[] { "U  ", " G ", "  U", Character.valueOf('U'), refined_uranium, Character.valueOf('G'), Block.glowStone });
		LanguageRegistry.addName(refined_plutonium, "Refined Plutonium");
		GameRegistry.addRecipe(new ItemStack(refined_plutonium, 1), new Object[] { "P P", " P ", "P P", Character.valueOf('P'), plutonium_ingot });
		LanguageRegistry.addName(graphite, "Graphite");
		GameRegistry.addSmelting(Item.flint.itemID, new ItemStack(graphite), 0);
		LanguageRegistry.addName(graphite_rod, "Graphite Rod");
		GameRegistry.addRecipe(new ItemStack(graphite_rod, 1), new Object[] { "GGG", "GGG", "GGG", Character.valueOf('G'), graphite });
		LanguageRegistry.addName(reactor_core, "Nuclear Reactor Core");
		GameRegistry.addRecipe(new ItemStack(reactor_core, 1), new Object[] { "UUU", "UPU", "UUU", Character.valueOf('U'), refined_uranium, Character.valueOf('P'), refined_plutonium });
		LanguageRegistry.addName(reactor_core_case, "Reactor Core Case");
		GameRegistry.addRecipe(new ItemStack(reactor_core_case, 1), new Object[] { " G ", " G ", " G ", Character.valueOf('G'), graphite_rod });
		LanguageRegistry.addName(iron_parts, "Iron Parts");
		GameRegistry.addRecipe(new ItemStack(iron_parts, 1), new Object[] { "III", " I ", Character.valueOf('I'), Item.ingotIron });
		GameRegistry.registerBlock(reactor);
		GameRegistry.addRecipe(new ItemStack(reactor, 1), new Object[] { "GMG", "CRC", "GMG", Character.valueOf('G'), graphite, Character.valueOf('M'), iron_parts, Character.valueOf('C'), reactor_core_case, Character.valueOf('R'), reactor_core });
		reactor.setUnlocalizedName("Nuclear Reactor");
		LanguageRegistry.addName(reactor, "Nuclear Reactor");
		GameRegistry.registerBlock(aluminium);
		aluminium.setUnlocalizedName("Aluminum");
		LanguageRegistry.addName(aluminium, "Aluminum");
		GameRegistry.addSmelting(Item.ingotIron.itemID, new ItemStack(aluminium), 0);
		GameRegistry.registerBlock(bomb_shell);
		GameRegistry.addRecipe(new ItemStack(bomb_shell, 1), new Object[] { "A A", " A ", "A A", Character.valueOf('A'), aluminium });
		bomb_shell.setUnlocalizedName("Bomb Shell");
		LanguageRegistry.addName(bomb_shell, "Bomb Shell");
		GameRegistry.registerBlock(c4);
		GameRegistry.addRecipe(new ItemStack(c4, 1), new Object[] { "GGG", "RRR", "GGG", Character.valueOf('G'), Item.gunpowder, Character.valueOf('R'), Item.redstone });
		c4.setUnlocalizedName("C4");
		LanguageRegistry.addName(c4, "C4");
		GameRegistry.registerBlock(nuclear_bomb);
		GameRegistry.addRecipe(new ItemStack(nuclear_bomb, 1), new Object[] { "BCB", "CRC", "BCB", Character.valueOf('B'), bomb_shell, Character.valueOf('C'), c4, Character.valueOf('R'), reactor });
		nuclear_bomb.setUnlocalizedName("Nuclear Bomb");
		LanguageRegistry.addName(nuclear_bomb, "Nuclear Bomb");
		LanguageRegistry.addName(rs_helmet, "Anti-Radiation Helmet");
		LanguageRegistry.addName(rs_legs, "Anti-Radiation Legggings");
		LanguageRegistry.addName(rs_chest, "Anti-Radiation Chest");
		LanguageRegistry.addName(rs_boots, "Anti-Radiation Boots");
		
		
		GameRegistry.addRecipe(new ItemStack(rs_helmet, 1), new Object[] { "WWW", "WGW", "I I", Character.valueOf('W'), Block.cloth, Character.valueOf('G'), Block.glass, Character.valueOf('I'), Item.ingotIron });
		GameRegistry.addRecipe(new ItemStack(rs_chest, 1), new Object[] { "W W", "WWW", "III", Character.valueOf('W'), Block.cloth, Character.valueOf('I'), Item.ingotIron });
		GameRegistry.addRecipe(new ItemStack(rs_legs, 1), new Object[] { "WWW", "W W", "I I", Character.valueOf('W'), Block.cloth, Character.valueOf('I'), Item.ingotIron });
		GameRegistry.addRecipe(new ItemStack(rs_boots, 1), new Object[] { "   ", "W W", "I I", Character.valueOf('W'), Block.cloth, Character.valueOf('I'), Item.ingotIron });
	}
}
