package grim3212.autoitem;

import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid = "AutoItemReplacer", name = "Automatic Item Replacer", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class AutomaticItemReplacer {
	public static int prevItem = 0;
	public static ItemStack prevItemStack = null;

	@SidedProxy(clientSide = "grim3212.autoitem.common.ClientProxy", serverSide = "grim3212.autoitem.common.CommonProxy")
	public static grim3212.autoitem.common.CommonProxy proxy;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Automatic Item Replacer";
		data.description = "A mod that automatically replaces blocks and items for you when you run out.";
		data.authorList.add("Grim3212");
		data.authorList.add("Borz0r");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Borz0r for the original mod.";
		data.logoFile = "/mods/logo.png";
	}

	@Init
	public void load(FMLInitializationEvent event) {

		proxy.registerRenderInformation();
	}
}
