package grim3212.lavaboat;

// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode 

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.src.ModLoader;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "LavaBoat", name = "Lava Boat", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class LavaBoat {
	@SidedProxy(clientSide = "grim3212.lavaboat.common.ClientProxy", serverSide = "grim3212.lavaboat.common.CommonProxy")
	public static grim3212.lavaboat.common.CommonProxy proxy;
	@Instance("LavaBoat")
	public static LavaBoat instance;

	public static Item LavaBoat;
	public int lavaBoatID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Lava Boat";
		data.description = "Adds in a new boat that you can drive across lava.";
		data.authorList.add("Grim3212");
		data.authorList.add("dougbenham");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to dougbenham for the original mod.";
		data.logoFile = "/mods/logo.png";

		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			lavaBoatID = config.get(Configuration.CATEGORY_ITEM, "Lava Boat ID", 9162).getInt(9162);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Lava Boat has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}
	
	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		
		LavaBoat = (new ItemLavaBoat(3037)).setUnlocalizedName("LavaBoat");
		
		GameRegistry.addRecipe(new ItemStack(LavaBoat, 1), new Object[] { "B B", "BBB", Character.valueOf('B'), Block.cobblestone });

		LanguageRegistry.addName(LavaBoat, "Lava Boat");
		EntityRegistry.registerModEntity(EntityLavaBoat.class, "LavaBoat", 86, this, 400, 20, true);
	}
}
