package grim3212.masks;

import java.util.logging.Level;

import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.EnumHelper;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Masks", name = "Masks", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Masks {
	@SidedProxy(clientSide = "grim3212.masks.common.ClientProxy", serverSide = "grim3212.masks.common.CommonProxy")
	public static grim3212.masks.common.CommonProxy proxy;
	@Instance("Masks")
	public static Masks instance;

	public static Item blazemask;
	public static Item cavemask;
	public static Item chickmask;
	public static Item cowmask;
	public static Item creepermask;
	public static Item emptymask;
	public static Item endermask;
	public static Item ghastmask;
	public static Item magmamask;
	public static Item pigmask;
	public static Item sheepmask;
	public static Item shroommask;
	public static Item skelemask;
	public static Item slimemask;
	public static Item spidermask;
	public static Item squidmask;
	public static Item villmask;
	public static Item wolfmask;
	public static Item zombmask;
	public static Item zombpigmask;

	public int blazemaskID, cavemaskID, chickmaskID, cowmaskID, creepermaskID, emptymaskID, endermaskID, ghastmaskID, magmamaskID, pigmaskID, sheepmaskID, shroommaskID, skelemaskID, slimemaskID, spidermaskID, squidmaskID, villmaskID, wolfmaskID, zombmaskID, zombpigmaskID;

	static EnumArmorMaterial masks = EnumHelper.addArmorMaterial("masks", 5, new int[] { 1, 3, 2, 1 }, 15);

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Masks";
    	data.description = "Adds in a bunch of masks with the face of mobs from Minecraft... (Scare your friends on Multiplayer)";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Nandonalt");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Nandonalt for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			blazemaskID = config.get(Configuration.CATEGORY_ITEM, "Blaze Mask ID", 9134).getInt(9134);
			cavemaskID = config.get(Configuration.CATEGORY_ITEM, "Cave Spider Mask ID", 9135).getInt(9135);
			chickmaskID = config.get(Configuration.CATEGORY_ITEM, "Chicken Mask ID", 9136).getInt(9136);
			cowmaskID = config.get(Configuration.CATEGORY_ITEM, "Cow Mask ID", 9137).getInt(9137);
			creepermaskID = config.get(Configuration.CATEGORY_ITEM, "Creeper Mask ID", 9138).getInt(9138);
			emptymaskID = config.get(Configuration.CATEGORY_ITEM, "Empty Mask ID", 9139).getInt(9139);
			endermaskID = config.get(Configuration.CATEGORY_ITEM, "Ender Mask ID", 9140).getInt(9140);
			ghastmaskID = config.get(Configuration.CATEGORY_ITEM, "Ghast Mask ID", 9141).getInt(9141);
			magmamaskID = config.get(Configuration.CATEGORY_ITEM, "Magma Cube Mask ID", 9142).getInt(9142);
			pigmaskID = config.get(Configuration.CATEGORY_ITEM, "Pig Mask ID", 9143).getInt(9143);
			sheepmaskID = config.get(Configuration.CATEGORY_ITEM, "Sheep Mask ID", 9144).getInt(9144);
			shroommaskID = config.get(Configuration.CATEGORY_ITEM, "Mooshroom Mask ID", 9145).getInt(9145);
			skelemaskID = config.get(Configuration.CATEGORY_ITEM, "Skeleton Mask ID", 9146).getInt(9146);
			slimemaskID = config.get(Configuration.CATEGORY_ITEM, "Slime Mask ID", 9147).getInt(9147);
			spidermaskID = config.get(Configuration.CATEGORY_ITEM, "Spider Mask ID", 9148).getInt(9148);
			squidmaskID = config.get(Configuration.CATEGORY_ITEM, "Squid Mask ID", 9149).getInt(9149);
			villmaskID = config.get(Configuration.CATEGORY_ITEM, "Villager Mask ID", 9150).getInt(9150);
			wolfmaskID = config.get(Configuration.CATEGORY_ITEM, "Wolf Mask ID", 9151).getInt(9151);
			zombmaskID = config.get(Configuration.CATEGORY_ITEM, "Zombie Mask ID", 9152).getInt(9152);
			zombpigmaskID = config.get(Configuration.CATEGORY_ITEM, "Zombie Pigman Mask ID", 9153).getInt(9153);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Masks has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();

		blazemask = (new MaskArmor(blazemaskID, masks, 3, 0)).setUnlocalizedName("Blaze Mask");
		cavemask = (new MaskArmor(cavemaskID, masks, 3, 0)).setUnlocalizedName("Cave Spider Mask");
		chickmask = (new MaskArmor(chickmaskID, masks, 3, 0)).setUnlocalizedName("Chicken Mask");
		cowmask = (new MaskArmor(cowmaskID, masks, 3, 0)).setUnlocalizedName("Cow Mask");
		creepermask = (new MaskArmor(creepermaskID, masks, 3, 0)).setUnlocalizedName("Creeper Mask");
		emptymask = (new MaskArmor(emptymaskID, masks, 3, 0)).setUnlocalizedName("Empty Mask");
		endermask = (new MaskArmor(endermaskID, masks, 3, 0)).setUnlocalizedName("Ender Mask");
		ghastmask = (new MaskArmor(ghastmaskID, masks, 3, 0)).setUnlocalizedName("Ghast Mask");
		magmamask = (new MaskArmor(magmamaskID, masks, 3, 0)).setUnlocalizedName("Magma Mask");
		pigmask = (new MaskArmor(pigmaskID, masks, 3, 0)).setUnlocalizedName("Pig Mask");
		sheepmask = (new MaskArmor(sheepmaskID, masks, 3, 0)).setUnlocalizedName("Sheep Mask");
		shroommask = (new MaskArmor(shroommaskID, masks, 3, 0)).setUnlocalizedName("Moo Shroom Mask");
		skelemask = (new MaskArmor(skelemaskID, masks, 3, 0)).setUnlocalizedName("Skeleton Mask");
		slimemask = (new MaskArmor(slimemaskID, masks, 3, 0)).setUnlocalizedName("Slime Mask");
		spidermask = (new MaskArmor(spidermaskID, masks, 3, 0)).setUnlocalizedName("SpiderMask");
		squidmask = (new MaskArmor(squidmaskID, masks, 3, 0)).setUnlocalizedName("Squid Mask");
		villmask = (new MaskArmor(villmaskID, masks, 3, 0)).setUnlocalizedName("Villager Mask");
		wolfmask = (new MaskArmor(wolfmaskID, masks, 3, 0)).setUnlocalizedName("Wolf Mask");
		zombmask = (new MaskArmor(zombmaskID, masks, 3, 0)).setUnlocalizedName("Zombie Mask");
		zombpigmask = (new MaskArmor(zombpigmaskID, masks, 3, 0)).setUnlocalizedName("Zombie Pig Mask");

		LanguageRegistry.addName(blazemask, "Blaze Mask");
		LanguageRegistry.addName(cavemask, "Cave Spider Mask");
		LanguageRegistry.addName(chickmask, "Chicken Mask");
		LanguageRegistry.addName(cowmask, "Cow Mask");
		LanguageRegistry.addName(creepermask, "Creeper Mask");
		LanguageRegistry.addName(emptymask, "Empty Mask");
		LanguageRegistry.addName(endermask, "Enderman Mask");
		LanguageRegistry.addName(ghastmask, "Ghast Mask");
		LanguageRegistry.addName(magmamask, "Magma Cube Mask");
		LanguageRegistry.addName(pigmask, "Pig Mask");
		LanguageRegistry.addName(sheepmask, "Sheep Mask");
		LanguageRegistry.addName(shroommask, "Mooshroom Mask");
		LanguageRegistry.addName(skelemask, "Skeleton Mask");
		LanguageRegistry.addName(slimemask, "Slime Mask");
		LanguageRegistry.addName(spidermask, "Spider Mask");
		LanguageRegistry.addName(squidmask, "Squid Mask");
		LanguageRegistry.addName(villmask, "Villager Mask");
		LanguageRegistry.addName(wolfmask, "Wolf Mask");
		LanguageRegistry.addName(zombmask, "Zombie Mask");
		LanguageRegistry.addName(zombpigmask, "Zombie Pig Mask");

		GameRegistry.addShapelessRecipe(new ItemStack(blazemask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 3), new ItemStack(Item.dyePowder, 1, 11), new ItemStack(Item.dyePowder, 1, 14) });
		GameRegistry.addShapelessRecipe(new ItemStack(cavemask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 4), new ItemStack(Item.dyePowder, 1, 1), new ItemStack(Item.dyePowder, 1, 6) });
		GameRegistry.addShapelessRecipe(new ItemStack(chickmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 15), new ItemStack(Item.dyePowder, 1, 1), new ItemStack(Item.dyePowder, 1, 14) });
		GameRegistry.addShapelessRecipe(new ItemStack(cowmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 15), new ItemStack(Item.dyePowder, 1, 3), new ItemStack(Item.dyePowder, 1, 0) });
		GameRegistry.addShapelessRecipe(new ItemStack(creepermask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 2), new ItemStack(Item.dyePowder, 1, 0), new ItemStack(Item.dyePowder, 1, 0) });
		GameRegistry.addRecipe(new ItemStack(emptymask, 1), new Object[] { "YXY", Character.valueOf('Y'), Item.silk, Character.valueOf('X'), Item.paper });
		GameRegistry.addShapelessRecipe(new ItemStack(endermask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 0), new ItemStack(Item.dyePowder, 1, 13), new ItemStack(Item.dyePowder, 1, 5) });
		GameRegistry.addShapelessRecipe(new ItemStack(ghastmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 15), new ItemStack(Item.dyePowder, 1, 8), new ItemStack(Item.dyePowder, 1, 7) });
		GameRegistry.addShapelessRecipe(new ItemStack(magmamask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 0), new ItemStack(Item.dyePowder, 1, 1), new ItemStack(Item.dyePowder, 1, 11) });
		GameRegistry.addShapelessRecipe(new ItemStack(pigmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 9), new ItemStack(Item.dyePowder, 1, 0) });
		GameRegistry.addShapelessRecipe(new ItemStack(sheepmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 9), new ItemStack(Item.dyePowder, 1, 15), new ItemStack(Item.dyePowder, 1, 3) });
		GameRegistry.addShapelessRecipe(new ItemStack(shroommask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 1), new ItemStack(Item.dyePowder, 1, 0), new ItemStack(Item.dyePowder, 1, 15) });
		GameRegistry.addShapelessRecipe(new ItemStack(skelemask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 15), new ItemStack(Item.dyePowder, 1, 8) });
		GameRegistry.addShapelessRecipe(new ItemStack(slimemask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 2), new ItemStack(Item.dyePowder, 1, 10) });
		GameRegistry.addShapelessRecipe(new ItemStack(spidermask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 1), new ItemStack(Item.dyePowder, 1, 0), new ItemStack(Item.dyePowder, 1, 8) });
		GameRegistry.addShapelessRecipe(new ItemStack(squidmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 4), new ItemStack(Item.dyePowder, 1, 6), new ItemStack(Item.dyePowder, 1, 12) });
		GameRegistry.addShapelessRecipe(new ItemStack(villmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 10), new ItemStack(Item.dyePowder, 1, 3), new ItemStack(Item.dyePowder, 1, 14) });
		GameRegistry.addShapelessRecipe(new ItemStack(wolfmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 0), new ItemStack(Item.dyePowder, 1, 3), new ItemStack(Item.dyePowder, 1, 7) });
		GameRegistry.addShapelessRecipe(new ItemStack(zombmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 2), new ItemStack(Item.dyePowder, 1, 0) });
		GameRegistry.addShapelessRecipe(new ItemStack(zombpigmask, 1), new Object[] { emptymask, new ItemStack(Item.dyePowder, 1, 10), new ItemStack(Item.dyePowder, 1, 9), new ItemStack(Item.dyePowder, 1, 8) });

	}
}
