// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces deadcode 

package grim3212.gunreeds;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "GunpowderReed", name = "Gunpowder Reeds", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class GunpowderReed
{
	@SidedProxy(clientSide = "grim3212.gunreeds.common.ClientProxy", serverSide = "grim3212.gunreeds.common.CommonProxy")
	public static grim3212.gunreeds.common.CommonProxy proxy;
	@Instance("GunpowderReed")
	public static GunpowderReed instance;
	
	public static Item greedItem;
    public static Block greedBlock;
    public int greedItemID;
    public static int greedBlockID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Gunpowder Reeds";
    	data.description = "Adds in a new plant that is basically a plant form of gunpowder.  It looks like the vanilla reeds but black.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Prowne");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Prowne for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			greedBlockID = config.get(Configuration.CATEGORY_BLOCK, "Gunpowder Reeds Block ID", 2651).getInt(2651);
			greedItemID = config.get(Configuration.CATEGORY_ITEM, "Gunpowder Reeds Item ID", 9000).getInt(9000);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Gunpowder Reeds has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}
	
    
	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
    	GameRegistry.registerWorldGenerator(new GunReedsGenerator());
    	
    	greedItem = (new GreedReed(greedItemID, Block.reed)).setUnlocalizedName("GunpowderReeds");
        greedBlock = (new GunpowderReeds(greedBlockID, 1)).setStepSound(Block.soundGrassFootstep).setHardness(0.0F).setLightValue(0.5F).setResistance(2000F).setUnlocalizedName("Greed Block");
    	
        GameRegistry.registerBlock(greedBlock);
        LanguageRegistry.addName(greedBlock, "Greed Block");
        LanguageRegistry.addName(greedItem, "Gunpowder Reeds");
        GameRegistry.addRecipe(new ItemStack(Item.gunpowder, 1), new Object[] {
            "X", Character.valueOf('X'), greedItem
        });
        GameRegistry.addRecipe(new ItemStack(greedItem, 1), new Object[] {
            "XXX", "XWX", "XXX", Character.valueOf('X'), Item.gunpowder, Character.valueOf('W'), Item.reed
        });
    }
}
