package grim3212.codknives;

import java.util.logging.Level;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Knives", name = "Call of Duty Knives", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Knives {

	@SidedProxy(clientSide = "grim3212.codknives.common.ClientProxy", serverSide = "grim3212.codknives.common.CommonProxy")
	public static grim3212.codknives.common.CommonProxy proxy;
	@Instance("Knives")
	public static Knives instance;

	public static Item tomahawk;
	public static Item knife;
	public static Item bknife;
	public static Item Bknife;
	public static Item grip;
	public static Item bknifefull;

	public int tomahawkID;
	public int knifeID;
	public int bknifeID;
	public int BknifeID;
	public int gripID;
	public int bknifefullID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Call of Duty Knives";
    	data.description = "Adds in a couple new weapons from the Call of Duty franchise which include ballistic knives, tomahawks, and also throwing knives, a little glitchy but still works.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Mods4U1121");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Mods4U1121 for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			tomahawkID = config.get(Configuration.CATEGORY_ITEM, "Tomahawk ID", 9032).getInt(9032);
			knifeID = config.get(Configuration.CATEGORY_ITEM, "Knife ID", 9033).getInt(9033);
			bknifeID = config.get(Configuration.CATEGORY_ITEM, "Ballistic Knife ID", 9034).getInt(9034);
			BknifeID = config.get(Configuration.CATEGORY_ITEM, "Ballistic Knife Part ID", 9035).getInt(9035);
			gripID = config.get(Configuration.CATEGORY_ITEM, "Grip ID", 9036).getInt(9036);
			bknifefullID = config.get(Configuration.CATEGORY_ITEM, "Ballistic Knife Full ID", 9037).getInt(9037);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Call of Duty Knives has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		
		bknifefull = (new ItembKnifeFull(bknifefullID)).setUnlocalizedName("bknifefull").setCreativeTab(CreativeTabs.tabCombat);
		grip = (new GenericItem(gripID)).setUnlocalizedName("grip").setCreativeTab(CreativeTabs.tabMaterials);
		Bknife = (new GenericItem(BknifeID)).setUnlocalizedName("Bknife").setCreativeTab(CreativeTabs.tabCombat);
		bknife = (new ItembKnife(bknifeID)).setUnlocalizedName("bknife").setCreativeTab(CreativeTabs.tabMaterials);
		knife = (new ItemKnife(knifeID)).setUnlocalizedName("knife").setCreativeTab(CreativeTabs.tabCombat);
		tomahawk = (new ItemTomahawk(tomahawkID)).setUnlocalizedName("tomahawk").setCreativeTab(CreativeTabs.tabCombat);
		
		EntityRegistry.registerModEntity(EntityKnife.class, "Knife", 5, this, 400, 20, true);
		EntityRegistry.registerModEntity(EntityBKnife.class, "BallisticKnife", 4, this, 400, 20, true);
		EntityRegistry.registerModEntity(EntityTomahawk.class, "Tomahawk", 3, this, 400, 20, true);

		LanguageRegistry.addName(tomahawk, "Tomahawk");
		GameRegistry.addRecipe(new ItemStack(tomahawk, 1), new Object[] { "XX ", "XY ", " Y ", Character.valueOf('X'), Item.ingotIron, Character.valueOf('Y'), grip });
		LanguageRegistry.addName(knife, "Throwing Knives");
		GameRegistry.addRecipe(new ItemStack(knife, 4), new Object[] { "Y", "X", Character.valueOf('Y'), Item.ingotIron, Character.valueOf('X'), grip });
		LanguageRegistry.addName(bknife, "Ballistic Knife Holder");
		GameRegistry.addRecipe(new ItemStack(bknife, 1), new Object[] { "#X ", " Y ", " R ", Character.valueOf('X'), Item.bucketEmpty, Character.valueOf('Y'), new ItemStack(Item.dyePowder, 1, 0), Character.valueOf('#'), Item.redstone, Character.valueOf('R'), grip });
		LanguageRegistry.addName(Bknife, "Ballistic Knife Blade");
		GameRegistry.addRecipe(new ItemStack(Bknife, 4), new Object[] { "X", "X", "Y", Character.valueOf('X'), Item.ingotIron, Character.valueOf('Y'), grip });
		LanguageRegistry.addName(grip, "Grip");
		GameRegistry.addRecipe(new ItemStack(grip, 2), new Object[] { "Y", "Y", Character.valueOf('Y'), Item.leather });
		LanguageRegistry.addName(bknifefull, "Loaded Ballistic Knife");
	}

}
