package grim3212.chisel;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "ChiselCore", name = "Chisel", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class ChiselCore
{
	@SidedProxy(clientSide = "grim3212.chisel.common.ClientProxy", serverSide = "grim3212.chisel.common.CommonProxy")
	public static grim3212.chisel.common.CommonProxy proxy;
	@Instance("ChiselCore")
	public static ChiselCore instance;
	
    public static Item Chisel;
    public static Item IronOre;
    public static Item GoldOre;
    public static Item DiamondChisel;
    
    public int ChiselID;
    public int IronOreID;
    public int GoldOreID;
    public int DiamondChiselID;
    
    @PreInit
	public void preInit(FMLPreInitializationEvent event) {
    	ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Chisel";
    	data.description = "Adds in a new way to get the items out of ore blocks.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Nandonalt");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Nandonalt for the original mod.";
    	data.logoFile = "/mods/logo.png";
    	
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			ChiselID = config.get(Configuration.CATEGORY_ITEM, "Chisel ID", 9130).getInt(9130);
			IronOreID = config.get(Configuration.CATEGORY_ITEM, "Iron Ore Item ID", 9131).getInt(9131);
			GoldOreID = config.get(Configuration.CATEGORY_ITEM, "Gold Ore Item ID", 9132).getInt(9132);
			DiamondChiselID = config.get(Configuration.CATEGORY_ITEM, "Diamond Chisel ID", 9133).getInt(9133);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Chisel has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}
    
    @Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		
		DiamondChisel = (new Chisel(DiamondChiselID, 4)).setUnlocalizedName("DiamondChisel");
		GoldOre = (new ChiselItem(GoldOreID)).setUnlocalizedName("IGoldOre");
		IronOre = (new ChiselItem(IronOreID)).setUnlocalizedName("IIronOre");
		Chisel = (new Chisel(ChiselID, 1)).setUnlocalizedName("Chisel");
		
        LanguageRegistry.addName(Chisel, "Iron Chisel");
        LanguageRegistry.addName(DiamondChisel, "Diamond Chisel");
        LanguageRegistry.addName(IronOre, "Iron Ore");
        LanguageRegistry.addName(GoldOre, "Gold Ore");
        chiselAPI.RegisterBlock(56, 1, Item.itemsList[264], 1, 0);
        chiselAPI.RegisterBlock(129, 1, Item.itemsList[388], 1, 0);
        chiselAPI.RegisterBlock(153, 87, Item.itemsList[406], 1, 0);
        chiselAPI.RegisterBlock(14, 1, GoldOre, 1, 0);
        chiselAPI.RegisterBlock(15, 1, IronOre, 1, 0);
        chiselAPI.RegisterBlock(73, 1, Item.itemsList[331], 4, 0);
        chiselAPI.RegisterBlock(74, 1, Item.itemsList[331], 4, 0);
        chiselAPI.RegisterBlock(16, 1, Item.itemsList[263], 1, 0);
        chiselAPI.RegisterBlock(21, 1, Item.itemsList[351], 3, 4);
        AddRecipes();
    }

    public void AddRecipes()
    {
        GameRegistry.addRecipe(new ItemStack(Chisel, 1), new Object[]
                {
                    " B", "I ", Character.valueOf('B'), Item.itemsList[265], Character.valueOf('I'), Item.itemsList[280]
                });
        GameRegistry.addRecipe(new ItemStack(DiamondChisel, 1), new Object[]
                {
                    " B", "I ", Character.valueOf('B'), Item.itemsList[264], Character.valueOf('I'), Item.itemsList[280]
                });
        GameRegistry.addSmelting(IronOre.itemID, new ItemStack(Item.ingotIron), 0.4F);
        GameRegistry.addSmelting(GoldOre.itemID, new ItemStack(Item.ingotGold), 1F);
    }
}
