package grim3212.togglerack;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;


@Mod(modid = "ToggleRack", name = "Toggle Rack", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class ToggleRack{
	
	@SidedProxy(clientSide = "grim3212.togglerack.common.ClientProxy", serverSide = "grim3212.togglerack.common.CommonProxy")
	public static grim3212.togglerack.common.CommonProxy proxy;
	@Instance("ToggleRack")
	public static ToggleRack instance;
	
	
	public static Block togglerack;
	public int toggleID;
	
	
	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Toggle Rack";
		data.description = "Adds in a new block that when activated with redstone has fire appear above it.";
		data.authorList.add("Grim3212");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Me for the original mod.";
		data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			toggleID = config.get(Configuration.CATEGORY_BLOCK, "Toggle Rack ID", 2650).getInt(2650);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Toggle Rack has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}
	
	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		
		togglerack = new BlockToggleRack(toggleID, 0).setHardness(0.6F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("togglerack").setCreativeTab(CreativeTabs.tabRedstone);
		LanguageRegistry.addName(togglerack, "Toggleable Netherack");
		GameRegistry.registerBlock(togglerack);
		GameRegistry.addRecipe(new ItemStack(togglerack, 4), new Object[]
            {
                 "QQQ", "QAQ", "QQQ", Character.valueOf('A'), Item.redstone, Character.valueOf('B'), Item.ingotGold, Character.valueOf('Q'), Block.netherrack
            });
	}

}
