package grim3212.chocolate;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Chocolate", name = "Chocolate", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Chocolate {
	@SidedProxy(clientSide = "grim3212.chocolate.common.ClientProxy", serverSide = "grim3212.chocolate.common.CommonProxy")
	public static grim3212.chocolate.common.CommonProxy proxy;
	@Instance("Chocolate")
	public static Chocolate instance;
	
	public static Block CocoaBlock;
	public static Block CocoaSaplingBlock;
	public static Block CBarMould;
	public static Block ChocolateCake;
	public static Block ChocolateBlock;
	public static Item CocoaFruit;
	public static Item CocoaDust;
	public static Item BowlChocolate;
	public static Item BowlChocolateHot;
	public static Item ChocolateBar;
	public static Item ChocolateBarWraped;
	public static Item ChocolateBall;
	public static Item BowlMilk;
	
	public int cocoaBlockID;
	public int cocoaSaplingBlockID;
	public int cBarMouldID;
	public int chocolateCakeID;
	public int chocolateBlockID;
	public int cocoaFruitID;
	public int cocoaDustID;
	public int bowlChocolateID;
	public int bowlChocolateHotID;
	public int chocolateBarID;
	public int chocolateBarWrappedID;
	public int chocolateBallID;
	public int bowlMilkID;

	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = "1.0";
		data.name = "Chocolate";
		data.description = "Adds in a bunch of different things revolving around chocolate... YUM!";
		data.authorList.add("Grim3212");
		data.authorList.add("Nandonalt");
		data.url = "http://grim3212.wikispaces.com/";
		data.credits = "Thanks to Nandonalt for the original mod.";
		data.logoFile = "/mods/logo.png";

		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			cocoaBlockID = config.get(Configuration.CATEGORY_BLOCK, "Cocoa Block ID", 2729).getInt(2729);
			cocoaSaplingBlockID = config.get(Configuration.CATEGORY_BLOCK, "Cocoa Sapling Block ID", 2730).getInt(2730);
			cBarMouldID = config.get(Configuration.CATEGORY_BLOCK, "Chocolate Bar Mould ID", 2731).getInt(2731);
			chocolateCakeID = config.get(Configuration.CATEGORY_BLOCK, "Chocolate Cake ID", 2732).getInt(2732);
			chocolateBlockID = config.get(Configuration.CATEGORY_BLOCK, "Chocolate Block ID", 2733).getInt(2733);
			
			cocoaFruitID = config.get(Configuration.CATEGORY_ITEM, "Cocoa Fruit ID", 9154).getInt(9154);
			cocoaDustID = config.get(Configuration.CATEGORY_ITEM, "Cocoa Dust ID", 9155).getInt(9155);
			bowlChocolateID = config.get(Configuration.CATEGORY_ITEM, "Chocolate Bowl ID", 9156).getInt(9156);
			bowlChocolateHotID = config.get(Configuration.CATEGORY_ITEM, "Chocolate Bowl Hot ID", 9157).getInt(9157);
			chocolateBarID = config.get(Configuration.CATEGORY_ITEM, "Chocolate Bar ID", 9158).getInt(9158);
			chocolateBarWrappedID = config.get(Configuration.CATEGORY_ITEM, "Chocolate Bar Wrapped ID", 9159).getInt(9159);
			chocolateBallID = config.get(Configuration.CATEGORY_ITEM, "Chocolate Ball ID", 9160).getInt(9160);
			bowlMilkID = config.get(Configuration.CATEGORY_ITEM, "Milk Bowl ID", 9161).getInt(9161);
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Chocolate has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		GameRegistry.registerWorldGenerator(new CocoaGenerator());
		
		CocoaFruit = (new ItemCocoaFruit(cocoaFruitID)).setUnlocalizedName("CocoaFruit").setCreativeTab(CreativeTabs.tabDecorations);
		CocoaDust = (new ItemGeneric(cocoaDustID)).setUnlocalizedName("CocoaDust").setCreativeTab(CreativeTabs.tabMaterials);
		BowlChocolate = (new ItemBowlChocolate(bowlChocolateID, 0)).setUnlocalizedName("BowlChoc").setCreativeTab(CreativeTabs.tabMaterials);
		ChocolateBar = (new ItemChocolateBar(chocolateBarID, 2, 8)).setUnlocalizedName("ChocolateBar").setCreativeTab(CreativeTabs.tabFood);
		ChocolateBarWraped = (new ItemChocolateBar(chocolateBarWrappedID, 4, 8)).setUnlocalizedName("ChocolateBarWrap").setCreativeTab(CreativeTabs.tabFood);
		ChocolateBall = (new ItemChocolateBar(chocolateBallID, 1, 2)).setUnlocalizedName("ChocolateBall").setCreativeTab(CreativeTabs.tabMaterials);
		BowlMilk = (new ItemBowlMilk(bowlMilkID, -1)).setUnlocalizedName("BowlMilk").setCreativeTab(CreativeTabs.tabMaterials);
		
		CocoaBlock = (new BlockCocoa(cocoaBlockID, 0)).setHardness(1.0F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("BlockCocoa");
		CocoaSaplingBlock = (new BlockCocoaSapling(cocoaSaplingBlockID, Material.plants)).setHardness(0.0F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("BlockCocoaSapling");
		CBarMould = (new BlockCBarMould(cBarMouldID)).setHardness(1.0F).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("BlockCBarMould").setCreativeTab(CreativeTabs.tabDecorations);
		ChocolateCake = (new BlockChocolateCake(chocolateCakeID, 121)).setHardness(0.5F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("ChocolateCake").setCreativeTab(CreativeTabs.tabFood);
		ChocolateBlock = (new BlockGeneric(chocolateBlockID, Material.cake)).setHardness(0.5F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("ChocolateBlock").setCreativeTab(CreativeTabs.tabBlock);
		BowlChocolateHot = (new ItemBowlChocolate(bowlChocolateHotID, 1)).setUnlocalizedName("BowlChoch").setContainerItem(Item.itemsList[281]).setCreativeTab(CreativeTabs.tabMaterials);

		GameRegistry.registerBlock(CocoaBlock);
		GameRegistry.registerBlock(CBarMould);
		GameRegistry.registerBlock(CocoaSaplingBlock);
		GameRegistry.registerBlock(ChocolateCake);
		GameRegistry.registerBlock(ChocolateBlock);
		LanguageRegistry.addName(CocoaFruit, "Cocoa Fruit");
		LanguageRegistry.addName(CBarMould, "Chocolate Bar Mould");
		LanguageRegistry.addName(CocoaDust, "Cocoa Powder");
		LanguageRegistry.addName(BowlChocolate, "Bowl of Chocolate Milk");
		LanguageRegistry.addName(BowlChocolateHot, "Bowl of Hot Chocolate Milk");
		LanguageRegistry.addName(ChocolateBar, "Chocolate Bar");
		LanguageRegistry.addName(ChocolateBall, "Chocolate Ball");
		LanguageRegistry.addName(ChocolateBarWraped, "Wrapped Chocolate Bar");
		LanguageRegistry.addName(ChocolateCake, "Chocolate Cake");
		LanguageRegistry.addName(ChocolateBlock, "Chocolate Block");
		LanguageRegistry.addName(BowlMilk, "Bowl of Milk");
		GameRegistry.addSmelting(BowlChocolate.itemID, new ItemStack(BowlChocolateHot), 0);
		AddRecipes();
	}

	public void AddRecipes() {
		GameRegistry.addRecipe(new ItemStack(CBarMould, 1), new Object[] { " I ", " I ", "XXX", Character.valueOf('X'), Block.cobblestone, Character.valueOf('I'), Block.stone });
		GameRegistry.addRecipe(new ItemStack(CocoaDust, 2), new Object[] { "X", Character.valueOf('X'), CocoaFruit });
		GameRegistry.addRecipe(new ItemStack(BowlChocolate), new Object[] { " X ", "XAX", " B ", Character.valueOf('X'), CocoaDust, Character.valueOf('A'), Item.sugar, Character.valueOf('B'), BowlMilk });
		GameRegistry.addShapelessRecipe(new ItemStack(Item.dyePowder, 3, 3), new Object[] { new ItemStack(CocoaDust), new ItemStack(CocoaDust) });
		GameRegistry.addRecipe(new ItemStack(ChocolateBall, 2), new Object[] { "X", Character.valueOf('X'), BowlChocolateHot });
		GameRegistry.addRecipe(new ItemStack(ChocolateCake, 1), new Object[] { "BXB", "SES", "WWW", Character.valueOf('B'), ChocolateBall, Character.valueOf('X'), Item.bucketMilk, Character.valueOf('S'), Item.sugar, Character.valueOf('E'), Item.egg, Character.valueOf('W'), Item.wheat });
		GameRegistry.addRecipe(new ItemStack(ChocolateBlock, 1), new Object[] { "XXX", "XXX", "XXX", Character.valueOf('X'), ChocolateBar });
		GameRegistry.addRecipe(new ItemStack(ChocolateBar, 9), new Object[] { "X", Character.valueOf('X'), ChocolateBlock });
		GameRegistry.addRecipe(new ItemStack(BowlMilk, 1), new Object[] { "X", "M", Character.valueOf('X'), Item.bucketMilk, Character.valueOf('M'), Item.bowlEmpty });
	}
}
