package grim3212.machetes;

import java.util.logging.Level;

import net.minecraft.block.Block;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "Machetes", name = "Machetes", version = "1.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class Machetes {

	@SidedProxy(clientSide = "grim3212.machetes.common.ClientProxy", serverSide = "grim3212.machetes.common.CommonProxy")
	public static grim3212.machetes.common.CommonProxy proxy;
	@Instance("Machetes")
	public static Machetes instance;

	public static Item macheteGold;
	public static Item macheteIron;
	public static Item macheteDiamond;
	public static Item macheteStone;
	public static Item macheteWood;
	public static Item macheteSlime;
	
	public int macheteGoldID;
	public int macheteIronID;
	public int macheteDiamondID;
	public int macheteStoneID;
	public int macheteWoodID;
	public int macheteSlimeID;
	
	@PreInit
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
    	data.autogenerated = false;
    	data.version = "1.0";
    	data.name = "Machetes";
    	data.description = "A mod that adds in some machetes to quickly get through those pesky jungles.";
    	data.authorList.add("Grim3212");
    	data.authorList.add("Scokeev9");
    	data.url = "http://grim3212.wikispaces.com/";
    	data.credits = "Thanks to Scokeev9 for the original mod.";
    	data.logoFile = "/mods/logo.png";
		
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		try {
			config.load();
			macheteGoldID = config.get(Configuration.CATEGORY_ITEM, "Machete Gold ID", 9002).getInt(9002);
			macheteIronID = config.get(Configuration.CATEGORY_ITEM, "Machete Iron ID", 9003).getInt(9003);
			macheteDiamondID = config.get(Configuration.CATEGORY_ITEM, "Machete Diamond ID", 9004).getInt(9004);
			macheteStoneID = config.get(Configuration.CATEGORY_ITEM, "Machete Stone ID", 9005).getInt(9005);
			macheteWoodID = config.get(Configuration.CATEGORY_ITEM, "Machete Wood ID", 9006).getInt(9006);
			macheteSlimeID = config.get(Configuration.CATEGORY_ITEM, "Machete Slime ID", 9007).getInt(9007);
			
		} catch (Exception e) {
			FMLLog.log(Level.SEVERE, e, "Machetes has had a problem loading it's configuration");
		} finally {
			config.save();
		}
	}

	@Init
	public void load(FMLInitializationEvent event) {
		proxy.registerRenderInformation();
		
		macheteGold = (new ItemMachete(macheteGoldID, EnumToolMaterial.GOLD)).setUnlocalizedName("macheteGold").setMaxDamage(32);
		macheteIron = (new ItemMachete(macheteIronID, EnumToolMaterial.IRON)).setUnlocalizedName("macheteIron").setMaxDamage(250);
		macheteDiamond = (new ItemMachete(macheteDiamondID, EnumToolMaterial.EMERALD)).setUnlocalizedName("macheteDiamond").setMaxDamage(1561);
		macheteStone = (new ItemMachete(macheteStoneID, EnumToolMaterial.STONE)).setUnlocalizedName("macheteStone").setMaxDamage(131);
		macheteWood = (new ItemMachete(macheteWoodID, EnumToolMaterial.WOOD)).setUnlocalizedName("macheteWood").setMaxDamage(59);
		macheteSlime = (new ItemMachete(macheteSlimeID, EnumToolMaterial.IRON)).setUnlocalizedName("macheteSlime").setMaxDamage(99);
		
		LanguageRegistry.addName(macheteGold, "Gold Machete");
		LanguageRegistry.addName(macheteIron, "Iron Machete");
		LanguageRegistry.addName(macheteWood, "Wood Machete");
		LanguageRegistry.addName(macheteDiamond, "Diamond Machete");
		LanguageRegistry.addName(macheteStone, "Stone Machete");
		LanguageRegistry.addName(macheteSlime, "Slime Machete");
		
		GameRegistry.addRecipe(new ItemStack(macheteGold, 1), new Object[] { "  X", " X ", "#  ", Character.valueOf('X'), Item.ingotGold, Character.valueOf('#'), Item.stick });
		GameRegistry.addRecipe(new ItemStack(macheteDiamond, 1), new Object[] { "  X", " X ", "#  ", Character.valueOf('X'), Item.diamond, Character.valueOf('#'), Item.stick });
		GameRegistry.addRecipe(new ItemStack(macheteIron, 1), new Object[] { "  X", " X ", "#  ", Character.valueOf('X'), Item.ingotIron, Character.valueOf('#'), Item.stick });
		GameRegistry.addRecipe(new ItemStack(macheteStone, 1), new Object[] { "  X", " X ", "#  ", Character.valueOf('X'), Block.cobblestone, Character.valueOf('#'), Item.stick });
		GameRegistry.addRecipe(new ItemStack(macheteWood, 1), new Object[] { "  X", " X ", "#  ", Character.valueOf('X'), Block.planks, Character.valueOf('#'), Item.stick });
		GameRegistry.addRecipe(new ItemStack(macheteSlime, 1), new Object[] { "  X", " X ", "#  ", Character.valueOf('X'), Item.slimeBall, Character.valueOf('#'), Item.stick });
	}

}
